- type: trainer
  config:
    trainer_type: hf_trainer
    dataset_config:
      dataset_type: bagel
      dataset_format: yaml
      shuffle: false
      datasets:
      - path: lmms-lab/bagel-example
        data_type: hf
        kwargs:
          split: train
      processor_config:
        processor_name: /mnt/raid10/pufanyi/Bagel-ckpt/BAGEL-7B-MoT
        processor_type: bagel
        image_transform_args:
          image_stride: 16
          max_image_size: 1024
          min_image_size: 512
      packing: true
      packing_strategy: first_fit
      packing_length: 16384
    model_config:
      load_with_custom_loader:
        model_path: /mnt/raid10/pufanyi/Bagel-ckpt/BAGEL-7B-MoT
        model_type: bagel
        config:
          finetune_from_hf: false
          vae_path: /mnt/raid10/pufanyi/hf/hub/models--ByteDance-Seed--BAGEL-7B-MoT/snapshots/570026eca23479ee7df5a6ce9fb50a835530da30/ae.safetensors
          vit_path: HuggingFaceM4/siglip-so400m-14-980-flash-attn2-navit
          llm_path: Qwen/Qwen2.5-0.5B-Instruct
    per_device_train_batch_size: 1
    learning_rate: 1.0e-05
    weight_decay: 0.0
    gradient_accumulation_steps: 1
    gradient_checkpointing: true
    num_train_epochs: 1
    save_steps: 100
    save_total_limit: 1
    report_to: wandb
    output_dir: ./output/debug
    warmup_ratio: 0.0
    run_name: blip3o
    eval_strategy: 'no'
    logging_steps: 1
    group_by_length: true
    dataloader_num_workers: 2
    bf16: true
    lr_scheduler_type: cosine
    freeze_modules:
    - visual
    use_liger_kernel: false
    use_rmpad: false
    fsdp2: false
