- type: trainer
  config:
    trainer_type: hf_trainer

    # Dataset configuration - now includes the actual dataset definitions
    dataset_config:
      dataset_type: blip3o
      dataset_format: yaml # Uses 'yaml' format for both external files and inline definitions

      # Inline dataset definitions (no dataset_path needed)
      datasets:
        - path: /data/pufanyi/lmms-engine-mini/tools/blip-3o-data-prep/data/blip3o-60k
          data_folder: /data/pufanyi/lmms-engine-mini/tools/blip-3o-data-prep/data/blip3o-60k
          data_type: arrow

      # Processor configuration
      processor_config:
        processor_name: "BLIP3o/BLIP3o-NEXT-Pretrain-3B"
        processor_type: "blip3o"

      # Packing configuration
      packing: true
      packing_strategy: first_fit
      packing_length: 16384

    # Model configuration
    model_config:
      load_from_pretrained_path: "BLIP3o/BLIP3o-NEXT-Pretrain-3B"
      attn_implementation: "flash_attention_2"

    # Training arguments, mostly compatible with HuggingFace Trainer
    per_device_train_batch_size: 1
    learning_rate: 1.0e-06 # we should use 1.0 to makes YAML recognize it as a float
    weight_decay: 0.0
    gradient_accumulation_steps: 1
    gradient_checkpointing: true
    num_train_epochs: 1
    save_steps: 100
    save_total_limit: 1
    report_to: "wandb"
    output_dir: "./output/debug"
    warmup_ratio: 0.0
    run_name: "blip3o_config"
    eval_strategy: "no"
    logging_steps: 1
    group_by_length: true
    dataloader_num_workers: 8
    bf16: true
    lr_scheduler_type: "cosine"
    freeze_modules: ["visual"]
    use_liger_kernel: false
    use_rmpad: false
    fsdp2: false
    # fsdp_config:
    #   transformer_layer_cls_to_wrap: ["Qwen2_5_VLDecoderLayer"]
    #   reshard_after_forward: false
